#!/bin/bash

sudo apt update

sudo hostnamectl set-hostname manuelnginx

sudo apt-get install -y curl wget

echo "[req]
prompt = no
distinguished_name = dn
[dn]
C = ES
ST = Cantabria
L = Santander
O = educantabria
OU =
CN = manuelnginx.duckdns.org
emailAddress = ubuntu
" | sudo tee /etc/ssl/openssl.cnf

# Crear certificado autofirmado
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
  -keyout /etc/ssl/private/manuelnginx.duckdns.org.key \
  -out /etc/ssl/certs/manuelnginx.crt \
  -subj "/C=ES/ST=Cantabria/L=Santander/O=educantabria/CN=manuelnginx.duckdns.org/emailAddress=ubuntu@gmail.com"

# Crear carpeta duckdns con los permisos adecuados
sudo mkdir -m 700 /home/ubuntu/duckdns

# Establecer el propietario y grupo a ubuntu
sudo chown ubuntu:ubuntu /home/ubuntu/duckdns

echo 'echo url="https://www.duckdns.org/update?domains=exampledomain&token=a7c4d0ad-114e-40ef-ba1d-d217904a50f2&ip=" | curl -k -o  /home/ubuntu/duckdns/duck.log -K -' |  tee /home/ubuntu/duckdns/duck.sh

chmod 700 /home/ubuntu/duckdns/duck.sh
sudo chown ubuntu:ubuntu /home/ubuntu/duckdns/duck.sh

(crontab -u ubuntu -l ; echo "*/5 * * * * /home/ubuntu/duckdns/duck.sh >/dev/null 2>&1") | crontab -u ubuntu -

/home/ubuntu/duckdns/duck.sh

sudo apt update

sudo apt install nginx -y

echo 'server {
    if ($host = manuelnginx.duckdns.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = manuelnginx.duckdns.org) {
        return 301 https://$host$request_uri;
    } # manejado por Certbot

    listen 80;
    server_name manuelnginx.duckdns.org;
    return 301 https://$host$request_uri;


}

server {
listen 443 ssl;
server_name manuelnginx.duckdns.org;
    ssl_certificate /etc/ssl/certs/nmanuelnginx.crt;
 # manejado por Certbot
    ssl_certificate_key /etc/ssl/private/manuelnginx.duckdns.org.key; # manejado por Certbot

location /_mtrix {
proxy_pass http://10.13.2.247:8008;

proxy_set_header X-Forwarded-For $remote_addr;
client_max_body_size 10M;
}


}

server {
listen 8443 ssl;
server_name nginx215.duckdns.org;

ssl_certificate /etc/ssl/certs/manuelnginx.crt; # manejado por Certbot
ssl_certificate_key /etc/ssl/private/manuelnginx.duckdns.org.key; # mane>

location /_matrix {
proxy_pass http://10.13.2.247:8008;

proxy_set_header X-Forwarded-For $remote_addr;
client_max_body_size 10M;
}
}' | sudo tee /etc/nginx/sites-available/manuelnginx

sudo ln -s /etc/nginx/sites-available/manuelnginx /etc/nginx/sites-enabled/
sudo nginx -t

sudo systemctl restart nginx
# sudo systemctl status nginx

sudo apt update

sudo snap install --classic certbot

sudo ln -s /snap/bin/certbot /usr/bin/certbot

sudo certbot --nginx -d manuelnginx.duckdns.org --non-interactive --agree-tos --email ubuntu@gmail.com
