#!bin/bash

sudo apt update -y

sudo hostnamectl set-hostname ticketingequipo3.duckdns.org

sudo apt install apache2 \
                 ghostscript \
                 libapache2-mod-php \
                 mysql-server \
                 php \
                 php-bcmath \
                 php-curl \
                 php-imagick \
                 php-intl \
                 php-json \
                 php-mbstring \
                 php-mysql \
                 php-xml \
                 php-zip -y

sudo mkdir -p /srv/www
sudo chown www-data: /srv/www
curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www

echo '<VirtualHost *:80>
    DocumentRoot /srv/www/wordpress
    <Directory /srv/www/wordpress>
        Options FollowSymLinks
        AllowOverride Limit Options FileInfo
        DirectoryIndex index.php
        Require all granted
    </Directory>
    <Directory /srv/www/wordpress/wp-content>
        Options FollowSymLinks
        Require all granted
    </Directory>
</VirtualHost>' | sudo tee /etc/apache2/sites-available/wordpress.conf

sudo service apache2 reload

sudo a2ensite wordpress
sudo a2enmod rewrite
sudo a2dissite 000-default

sudo service apache2 reload

sudo mysql -u root <<EOF
CREATE DATABASE wordpress;
CREATE USER 'wordpress'@'localhost' IDENTIFIED BY '1234';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO 'wordpress'@'localhost';
FLUSH PRIVILEGES;
EOF

#!bin/bash

sudo service mysql start

sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php

sudo -u www-data sed -i 's/database_name_here/wordpress/' /srv/www/wordpress/wp-config.php
sudo -u www-data sed -i 's/username_here/wordpress/' /srv/www/wordpress/wp-config.php
sudo -u www-data sed -i 's/password_here/1234/' /srv/www/wordpress/wp-config.php

NEW_CONTENT=$(cat <<EOL
define('AUTH_KEY',         '^CnhENGhHdOnM@=?C&a5m|H-@wDD//gt%N7bMSbkwI;0hUvMEY]21,jDgt{Trdmj');
define('SECURE_AUTH_KEY',  'x:E/4)&hBqchejy2?+|82W%u+aP2_N@ lnnu8Td>:=!QlZhR.;F?}/oq2HA3sRjH');
define('LOGGED_IN_KEY',    'L,_TTUQ[U+z{CRZnzG-V;Awk;aYr$#3EUoCg;5glC*kBw2.1MplAID2Hb6$jC8xr');
define('NONCE_KEY',        'ta+,;5j#;}|/.5evx7nZ7NJ1#`g5~Q-VTGhTJq*t5wMlF!$7LZ_`wvnnvn)$-<Az');
define('AUTH_SALT',        'iC1}yS84_KXVlU)u:Gg~Hs7=j!Y3L=hC7Eura+uhQH.&pYw;51W|?<;<+|8]~@w9');
define('SECURE_AUTH_SALT', 'WO+oh3tc{_-Z/?mQLnM-|d0qEC5:+@a(+buyP]UZ3Y:WcJ7=%]gKYa=|Cvhq-T9,');
define('LOGGED_IN_SALT',   '~S:.Z!{:C]+_055 @eE_>|%x:8.pJ(O,gF3@R3/%~[|FkvDxO8%&3uiE3@0Z3s&~');
define('NONCE_SALT',       '=|<O8cU++zDUb`m-f+,0#j&u<|{!c-;!)*>LE:N3;uKM~g/z}H]I-+ad6~||t<+r');
EOL
)
